# Model Training


In [702]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier
from tabulate import tabulate
import numpy as np

In [703]:
processed_data="C:/Users/aaa/OneDrive/Desktop/Modular_Project_3/Data/Processed/processed_dataset.csv"
df=pd.read_csv(processed_data)

In [704]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Sample_ID             3000 non-null   float64
 1   Sequence              3000 non-null   float64
 2   GC_Content            3000 non-null   float64
 3   AT_Content            3000 non-null   float64
 4   Sequence_Length       3000 non-null   float64
 5   Num_A                 3000 non-null   float64
 6   Num_T                 3000 non-null   float64
 7   Num_C                 3000 non-null   float64
 8   Num_G                 3000 non-null   float64
 9   kmer_3_freq           3000 non-null   float64
 10  Mutation_Flag         3000 non-null   float64
 11  Disease_Risk          3000 non-null   int64  
 12  Class_Label_Bacteria  3000 non-null   float64
 13  Class_Label_Human     3000 non-null   float64
 14  Class_Label_Plant     3000 non-null   float64
 15  Class_Label_Virus    

In [705]:
y=df['Disease_Risk']

In [706]:
x=df.drop('Disease_Risk', axis=1)

In [707]:
x_train,x_test, y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=42)

In [708]:
x_train.shape
x_test.shape

(600, 15)

# Logistic Regression

In [709]:
lr=LogisticRegression()


In [710]:
lr

LogisticRegression()

In [711]:
lr.fit(x_test,y_test)

LogisticRegression()

In [712]:
y_pred_lr=lr.predict(x_test)

In [713]:
print("Accuracy:", accuracy_score(y_test, y_pred_lr))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_lr))
print("Classification Report:\n", classification_report(y_test, y_pred_lr))

Accuracy: 0.43333333333333335
Confusion Matrix:
 [[114  41  53]
 [ 71  64  54]
 [ 80  41  82]]
Classification Report:
               precision    recall  f1-score   support

           0       0.43      0.55      0.48       208
           1       0.44      0.34      0.38       189
           2       0.43      0.40      0.42       203

    accuracy                           0.43       600
   macro avg       0.43      0.43      0.43       600
weighted avg       0.43      0.43      0.43       600



In [714]:
# ['Logistic Regression', accuracy_score(y_test, y_pred_lr), confusion_matrix(y_test, y_pred_lr), classification_report(y_test, y_pred_lr)]

# RandomForestClassifier

In [715]:
rf=RandomForestClassifier()

In [716]:
rf

RandomForestClassifier()

In [717]:
rf.fit(x_test,y_test)

RandomForestClassifier()

In [718]:
y_pred_rf=rf.predict(x_test)

In [719]:
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))
print("Classification Report:\n", classification_report(y_test, y_pred_rf))

Accuracy: 1.0
Confusion Matrix:
 [[208   0   0]
 [  0 189   0]
 [  0   0 203]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       208
           1       1.00      1.00      1.00       189
           2       1.00      1.00      1.00       203

    accuracy                           1.00       600
   macro avg       1.00      1.00      1.00       600
weighted avg       1.00      1.00      1.00       600



In [720]:
# ['RandomForestClassifier', accuracy_score(y_test, y_pred_rf), confusion_matrix(y_test, y_pred_rf), classification_report(y_test, y_pred_rf)]

In [721]:
print(x.columns)

Index(['Sample_ID', 'Sequence', 'GC_Content', 'AT_Content', 'Sequence_Length',
       'Num_A', 'Num_T', 'Num_C', 'Num_G', 'kmer_3_freq', 'Mutation_Flag',
       'Class_Label_Bacteria', 'Class_Label_Human', 'Class_Label_Plant',
       'Class_Label_Virus'],
      dtype='object')


# GradientBoostingClassifier

In [722]:
gb=GradientBoostingClassifier(random_state=42)

In [723]:
gb

GradientBoostingClassifier(random_state=42)

In [724]:
gb.fit(x_test,y_test)

GradientBoostingClassifier(random_state=42)

In [725]:
y_pred_gb=gb.predict(x_test)

In [726]:
print("Accuracy:", accuracy_score(y_test, y_pred_gb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_gb))
print("Classification Report:\n", classification_report(y_test, y_pred_gb))

Accuracy: 0.88
Confusion Matrix:
 [[193   4  11]
 [ 20 157  12]
 [ 14  11 178]]
Classification Report:
               precision    recall  f1-score   support

           0       0.85      0.93      0.89       208
           1       0.91      0.83      0.87       189
           2       0.89      0.88      0.88       203

    accuracy                           0.88       600
   macro avg       0.88      0.88      0.88       600
weighted avg       0.88      0.88      0.88       600



In [727]:
# ['GradientBoostingClassifier', accuracy_score(y_test, y_pred_gb), confusion_matrix(y_test, y_pred_gb), classification_report(y_test, y_pred_gb)]

# DecisionTreeClassifier

In [728]:
dt = DecisionTreeClassifier(random_state=42)
dt
dt.fit(x_train, y_train)
y_pred_dt=dt.predict(x_test)

In [729]:
print("Accuracy:", accuracy_score(y_test, y_pred_dt))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_dt))
print("Classification Report:\n", classification_report(y_test, y_pred_dt))

Accuracy: 0.3233333333333333
Confusion Matrix:
 [[76 60 72]
 [72 67 50]
 [71 81 51]]
Classification Report:
               precision    recall  f1-score   support

           0       0.35      0.37      0.36       208
           1       0.32      0.35      0.34       189
           2       0.29      0.25      0.27       203

    accuracy                           0.32       600
   macro avg       0.32      0.32      0.32       600
weighted avg       0.32      0.32      0.32       600



In [730]:
# ['DecisionTreeClassifier', accuracy_score(y_test, y_pred_dt), confusion_matrix(y_test, y_pred_dt), classification_report(y_test, y_pred_dt)]

# AdaBoostClassifier

In [731]:
ad=AdaBoostClassifier()
ad
ad.fit(x_train, y_train)
y_pred_ad=ad.predict(x_test)

In [732]:
print("Accuracy:", accuracy_score(y_test, y_pred_ad))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_ad))
print("Classification Report:\n", classification_report(y_test, y_pred_ad))

Accuracy: 0.3416666666666667
Confusion Matrix:
 [[163  32  13]
 [152  27  10]
 [167  21  15]]
Classification Report:
               precision    recall  f1-score   support

           0       0.34      0.78      0.47       208
           1       0.34      0.14      0.20       189
           2       0.39      0.07      0.12       203

    accuracy                           0.34       600
   macro avg       0.36      0.33      0.27       600
weighted avg       0.36      0.34      0.27       600



In [733]:
# ['AdaBoostClassifier', accuracy_score(y_test, y_pred_ad), confusion_matrix(y_test, y_pred_ad), classification_report(y_test, y_pred_ad)]

# KNeighborsClassifier

In [734]:
knn=KNeighborsClassifier(n_neighbors=5)

In [735]:
knn
knn.fit(x_train, y_train)
y_pred_knn=knn.predict(x_test)

In [736]:
print("Accuracy:", accuracy_score(y_test, y_pred_knn))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_knn))
print("Classification Report:\n", classification_report(y_test, y_pred_knn))

Accuracy: 0.3233333333333333
Confusion Matrix:
 [[103  64  41]
 [ 87  57  45]
 [108  61  34]]
Classification Report:
               precision    recall  f1-score   support

           0       0.35      0.50      0.41       208
           1       0.31      0.30      0.31       189
           2       0.28      0.17      0.21       203

    accuracy                           0.32       600
   macro avg       0.31      0.32      0.31       600
weighted avg       0.31      0.32      0.31       600



In [737]:
# ['KNeighborsClassifier', accuracy_score(y_test, y_pred_knn), confusion_matrix(y_test, y_pred_knn), classification_report(y_test, y_pred_knn)]

# XGboost

In [738]:
xb=XGBClassifier(eval_metric="mlogloss", random_state=42)

In [739]:
xb
xb.fit(x_train, y_train)
y_pred_xb=xb.predict(x_test)

In [740]:
print("Accuracy:", accuracy_score(y_test, y_pred_xb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_xb))
print("Classification Report:\n", classification_report(y_test, y_pred_xb))

Accuracy: 0.35
Confusion Matrix:
 [[80 70 58]
 [77 70 42]
 [66 77 60]]
Classification Report:
               precision    recall  f1-score   support

           0       0.36      0.38      0.37       208
           1       0.32      0.37      0.34       189
           2       0.38      0.30      0.33       203

    accuracy                           0.35       600
   macro avg       0.35      0.35      0.35       600
weighted avg       0.35      0.35      0.35       600



In [741]:
# ['XGBClassifier', accuracy_score(y_test, y_pred_xb), confusion_matrix(y_test, y_pred_xb), classification_report(y_test, y_pred_xb)]

In [742]:
df.to_csv("C:/Users/aaa/OneDrive/Desktop/Modular_Project_3/Data/Splited/splited_dataset.csv", index=False)

In [743]:
results = [
    ['Logistic Regression', accuracy_score(y_test, y_pred_lr), confusion_matrix(y_test, y_pred_lr), classification_report(y_test, y_pred_lr)],
    ['RandomForestClassifier', accuracy_score(y_test, y_pred_rf), confusion_matrix(y_test, y_pred_rf), classification_report(y_test, y_pred_rf)],
    ['GradientBoostingClassifier', accuracy_score(y_test, y_pred_gb), confusion_matrix(y_test, y_pred_gb), classification_report(y_test, y_pred_gb)],
    ['DecisionTreeClassifier', accuracy_score(y_test, y_pred_dt), confusion_matrix(y_test, y_pred_dt), classification_report(y_test, y_pred_dt)],
    ['AdaBoostClassifier', accuracy_score(y_test, y_pred_ad), confusion_matrix(y_test, y_pred_ad), classification_report(y_test, y_pred_ad)],
    ['KNeighborsClassifier', accuracy_score(y_test, y_pred_knn), confusion_matrix(y_test, y_pred_knn), classification_report(y_test, y_pred_knn)],
    ['XGBClassifier', accuracy_score(y_test, y_pred_xb), confusion_matrix(y_test, y_pred_xb), classification_report(y_test, y_pred_xb)]
]

headers = ["Model", "Accuracy", "Confusion Matrix", "Classification Report"]

table = tabulate(results, headers=headers, tablefmt='grid', floatfmt='.7f')

In [744]:
print(table)

+----------------------------+------------+--------------------+-------------------------------------------------------+
| Model                      |   Accuracy | Confusion Matrix   | Classification Report                                 |
+============================+============+====================+=======================================================+
| Logistic Regression        |  0.4333333 | [[114  41  53]     | precision    recall  f1-score   support               |
|                            |            |  [ 71  64  54]     |                                                       |
|                            |            |  [ 80  41  82]]    |            0       0.43      0.55      0.48       208 |
|                            |            |                    |            1       0.44      0.34      0.38       189 |
|                            |            |                    |            2       0.43      0.40      0.42       203 |
|                            |  

In [745]:
results_dict = {model[0]: model[1] for model in results}
best_model = max(results_dict, key=results_dict.get)
print("Best Model:", best_model, "with Accuracy:", results_dict[best_model])

Best Model: RandomForestClassifier with Accuracy: 1.0


In [746]:
df.to_csv("C:/Users/aaa/OneDrive/Desktop/Modular_Project_3/Data/Splited/splited_dataset.csv", index=False)